
#define INP_IMAGE_SIZE 31
#define INP_IMAGE_CHANNEL 96
#define OUT_IMAGE_SIZE 27
#define FILTER_BATCH 256
#define FILTER_CHANNEL 48
#define FILTER_SIZE 5
#define STRIDE 1
#define STRIDE_NEW 5
#define GROUP 2

/*
#define INP_IMAGE_SIZE 227
#define INP_IMAGE_CHANNEL 3
#define OUT_IMAGE_SIZE 55
#define FILTER_BATCH 96
#define FILTER_SIZE 11
#define STRIDE 4
#define STRIDE_NEW 11

#define INP_IMAGE_SIZE 6
#define INP_IMAGE_CHANNEL 48
#define OUT_IMAGE_SIZE 2
#define FILTER_BATCH 40
#define FILTER_CHANNEL 24
#define FILTER_SIZE 5
#define STRIDE 1
#define STRIDE_NEW 5
#define GROUP 2
*/
