/*
#define INP_IMAGE_SIZE 15
#define INP_IMAGE_CHANNEL 3
#define OUT_IMAGE_SIZE 2
#define FILTER_BATCH 3
#define FILTER_SIZE 11
#define STRIDE 4
#define STRIDE_NEW 11
*/
#define INP_IMAGE_SIZE 15
#define INP_IMAGE_CHANNEL 256
#define OUT_IMAGE_SIZE 13
#define FILTER_BATCH 384
//#define FILTER_CHANNEL 256
#define FILTER_SIZE 3
#define STRIDE 1
#define STRIDE_NEW 3

