
#define INP_IMAGE_SIZE 15
#define INP_IMAGE_CHANNEL 384
#define OUT_IMAGE_SIZE 13
#define FILTER_BATCH 384
#define FILTER_CHANNEL 192
#define FILTER_SIZE 3
#define STRIDE 1
#define STRIDE_NEW 3
#define GROUP 2
/*
#define INP_IMAGE_SIZE 227
#define INP_IMAGE_CHANNEL 3
#define OUT_IMAGE_SIZE 55
#define FILTER_BATCH 96
#define FILTER_SIZE 11
#define STRIDE 4
#define STRIDE_NEW 11
*/
